#! /usr/bin/env bash

export DATA=${DATA:-${DATAROOT}/${RUN}atmanl_${cyc}}
source "${HOMEgfs}/ush/jjob_header.sh" -e "atmanlinit" -c "base atmanl atmanlinit"

##############################################
# Set variables used in the script
##############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
GDUMP="gdas"

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
   COMIN_OBS:COM_OBS_TMPL

RUN="gfs" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
   COMIN_ATMOS_HISTORY_PREV:COM_ATMOS_HISTORY_TMPL

RUN=${GDUMP} YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
   COMIN_ATMOS_ANALYSIS_PREV:COM_ATMOS_ANALYSIS_TMPL \

mkdir -m 775 -p "${COMIN_ATMOS_ANALYSIS_PREV}"

###############################################################
# Run relevant script

# Save PDY and cyc
sPDY=${PDY}
scyc=${cyc}

# Reset PDY and cyc
export PDY=${tPDY}
export cyc=${tcyc}

EXSCRIPT=${GDASATMINITPY:-${SCRgfs}/exglobal_atm_analysis_initialize.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

# Restore PDY and cyc
export PDY=${sPDY}
export cyc=${scyc}

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

exit 0
